INSERT IGNORE INTO adn (idgen, nomgen, adn, arn) VALUES 
(2915, 'CD96', 'TACCTCTTCTTTACCTTTATAACACGCCACATAATGTAATAAGTTTAAGTAAAG', 'AUGGAGAAGAAAUGGAAAUAUUGUGCGGUGUAUUACAUUAUUCAAAUUCAUUUC'),
(2916, 'TBC1D7', 'TACTGCCTCCTGAGGGTTTCCTTGAAGGCCAGACAAATGATACTTTTTCAGCCGAAGTCT', 'AUGACGGAGGACUCCCAAAGGAACUUCCGGUCUGUUUACUAUGAAAAAGUCGGCUUCAGA'),
(2939, 'noAUG', 'AACTCGATTGCACCGGGT', 'UUGAGCUAACGUGGCCCA'),
(3000, 'G24003B', 'TACTTCCCCCGCTGATAGTTTGCCCTCCAGGTCTATGGCCGCGACTTAGCACCTTTAGAGAAAATCATTGCCAGAACTGACCCGCGTAAAAGACGAGCGCCGTACTACCGGGCACCTCTATAGTCGTA',  'AUGAAGGGGGCGACUAUCAAACGGGAGGUCCAGAUACCGGCGCUGAAUCGUGGAAAUCUCUUUUAGUAACGGUCUUGACUGGGCGCAUUUUCUGCUCGCGGCAUGAUGGCCCGUGGAGAUAUCAGCAU'),
(3001, NULL, 'GGCTACGGTTACATTAGTTACGCTTA', 'CCGAUGCCAAUGUAAUCAAUGCGAAU');

