INSERT INTO adn (nomgen, adn) VALUES ('G24001B', 'TACCTCCCCTTGGCCCTGTTCAAGCGTCGTAG');
INSERT INTO adn (nomgen, adn) VALUES ('G24002B', 'TGCCAGTTACTTCAATTACTGACCTGCACTCTGAGCATTCAATAAACTGAGCCACCTTAGGAGC');
INSERT INTO adn (nomgen, adn) VALUES ('G24003B',  'TACTTCCCCCGCTGATAGTTTGCCCTCCAGGTCTATGGCCGCGACTTAGCACCTTTAGAGAAAATCATTGCCAGAACTGACCCGCGTAAAAGACGAGCGCCGTACTACCGGGCACCTCTATAGTCGTA');

